language: python
matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27
  - python: "3.4"
    env: TOXENV=py34
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.6"
    env: TOXENV=codestyle
    before_install: true

before_install:
  - wget "https://dist.udfs.io/go-udfs/v0.4.14/go-udfs_v0.4.14_linux-amd64.tar.gz" -O /tmp/udfs.tar.gz
  - mkdir -p $HOME/bin
  - pushd . && cd $HOME/bin && tar -xzvf /tmp/udfs.tar.gz && popd
  - export PATH="$HOME/bin/go-udfs:$PATH"

install:
  - pip install tox

script: tox
